// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Vec4_Response.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Vec4_Response.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

fog_msgs::msg::Vec4_Response::Vec4_Response()
{
    // m_success com.eprosima.idl.parser.typecode.PrimitiveTypeCode@3daa422a
    m_success = false;
    // m_message com.eprosima.idl.parser.typecode.StringTypeCode@27ce24aa
    m_message ="";

}

fog_msgs::msg::Vec4_Response::~Vec4_Response()
{


}

fog_msgs::msg::Vec4_Response::Vec4_Response(
        const Vec4_Response& x)
{
    m_success = x.m_success;
    m_message = x.m_message;
}

fog_msgs::msg::Vec4_Response::Vec4_Response(
        Vec4_Response&& x)
{
    m_success = x.m_success;
    m_message = std::move(x.m_message);
}

fog_msgs::msg::Vec4_Response& fog_msgs::msg::Vec4_Response::operator =(
        const Vec4_Response& x)
{

    m_success = x.m_success;
    m_message = x.m_message;

    return *this;
}

fog_msgs::msg::Vec4_Response& fog_msgs::msg::Vec4_Response::operator =(
        Vec4_Response&& x)
{

    m_success = x.m_success;
    m_message = std::move(x.m_message);

    return *this;
}

size_t fog_msgs::msg::Vec4_Response::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;


    return current_alignment - initial_alignment;
}

size_t fog_msgs::msg::Vec4_Response::getCdrSerializedSize(
        const fog_msgs::msg::Vec4_Response& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.message().size() + 1;


    return current_alignment - initial_alignment;
}

void fog_msgs::msg::Vec4_Response::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_success;
    scdr << m_message;

}

void fog_msgs::msg::Vec4_Response::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_success;
    dcdr >> m_message;
}

/*!
 * @brief This function sets a value in member success
 * @param _success New value for member success
 */
void fog_msgs::msg::Vec4_Response::success(
        bool _success)
{
    m_success = _success;
}

/*!
 * @brief This function returns the value of member success
 * @return Value of member success
 */
bool fog_msgs::msg::Vec4_Response::success() const
{
    return m_success;
}

/*!
 * @brief This function returns a reference to member success
 * @return Reference to member success
 */
bool& fog_msgs::msg::Vec4_Response::success()
{
    return m_success;
}

/*!
 * @brief This function copies the value in member message
 * @param _message New value to be copied in member message
 */
void fog_msgs::msg::Vec4_Response::message(
        const std::string& _message)
{
    m_message = _message;
}

/*!
 * @brief This function moves the value in member message
 * @param _message New value to be moved in member message
 */
void fog_msgs::msg::Vec4_Response::message(
        std::string&& _message)
{
    m_message = std::move(_message);
}

/*!
 * @brief This function returns a constant reference to member message
 * @return Constant reference to member message
 */
const std::string& fog_msgs::msg::Vec4_Response::message() const
{
    return m_message;
}

/*!
 * @brief This function returns a reference to member message
 * @return Reference to member message
 */
std::string& fog_msgs::msg::Vec4_Response::message()
{
    return m_message;
}

size_t fog_msgs::msg::Vec4_Response::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool fog_msgs::msg::Vec4_Response::isKeyDefined()
{
    return false;
}

void fog_msgs::msg::Vec4_Response::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}


