// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DroneCoordinates.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _DRONE_INTERFACES_MSG_DRONECOORDINATES_H_
#define _DRONE_INTERFACES_MSG_DRONECOORDINATES_H_

#include "Point.h"

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(DroneCoordinates_SOURCE)
#define DroneCoordinates_DllAPI __declspec( dllexport )
#else
#define DroneCoordinates_DllAPI __declspec( dllimport )
#endif // DroneCoordinates_SOURCE
#else
#define DroneCoordinates_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define DroneCoordinates_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace drone_interfaces {
    namespace msg {
        /*!
         * @brief This class represents the structure DroneCoordinates defined by the user in the IDL file.
         * @ingroup DRONECOORDINATES
         */
        class DroneCoordinates
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport DroneCoordinates();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~DroneCoordinates();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object drone_interfaces::msg::DroneCoordinates that will be copied.
             */
            eProsima_user_DllExport DroneCoordinates(
                    const DroneCoordinates& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object drone_interfaces::msg::DroneCoordinates that will be copied.
             */
            eProsima_user_DllExport DroneCoordinates(
                    DroneCoordinates&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object drone_interfaces::msg::DroneCoordinates that will be copied.
             */
            eProsima_user_DllExport DroneCoordinates& operator =(
                    const DroneCoordinates& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object drone_interfaces::msg::DroneCoordinates that will be copied.
             */
            eProsima_user_DllExport DroneCoordinates& operator =(
                    DroneCoordinates&& x);

            /*!
             * @brief This function copies the value in member id
             * @param _id New value to be copied in member id
             */
            eProsima_user_DllExport void id(
                    const std::string& _id);

            /*!
             * @brief This function moves the value in member id
             * @param _id New value to be moved in member id
             */
            eProsima_user_DllExport void id(
                    std::string&& _id);

            /*!
             * @brief This function returns a constant reference to member id
             * @return Constant reference to member id
             */
            eProsima_user_DllExport const std::string& id() const;

            /*!
             * @brief This function returns a reference to member id
             * @return Reference to member id
             */
            eProsima_user_DllExport std::string& id();
            /*!
             * @brief This function copies the value in member coordinates
             * @param _coordinates New value to be copied in member coordinates
             */
            eProsima_user_DllExport void coordinates(
                    const geometry_msgs::msg::Point& _coordinates);

            /*!
             * @brief This function moves the value in member coordinates
             * @param _coordinates New value to be moved in member coordinates
             */
            eProsima_user_DllExport void coordinates(
                    geometry_msgs::msg::Point&& _coordinates);

            /*!
             * @brief This function returns a constant reference to member coordinates
             * @return Constant reference to member coordinates
             */
            eProsima_user_DllExport const geometry_msgs::msg::Point& coordinates() const;

            /*!
             * @brief This function returns a reference to member coordinates
             * @return Reference to member coordinates
             */
            eProsima_user_DllExport geometry_msgs::msg::Point& coordinates();

            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const drone_interfaces::msg::DroneCoordinates& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            std::string m_id;
            geometry_msgs::msg::Point m_coordinates;
        };
    } // namespace msg
} // namespace drone_interfaces

#endif // _DRONE_INTERFACES_MSG_DRONECOORDINATES_H_